name: falasyam
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  timeline_list: ^0.0.5
  timeline: ^0.0.1
  url_launcher: ^5.4.5
  splashscreen: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: MrDafoe
      fonts:
          - asset: assets/fonts/MrDafoe-Regular.ttf

    - family: CutiveMono
      fonts:
          - asset: assets/fonts/CutiveMono-Regular.ttf
    - family: SourceCodePro
      fonts:
          - asset: assets/fonts/SourceCodePro-Regular.ttf
          - asset: assets/fonts/SourceCodePro-Black.ttf
            weight: 700